apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name }}-backend-external-worker
  name: {{ .Release.Name }}-backend-external-worker
spec:
  {{- if not .Values.services.worker.external.autoscaling.enabled }}
  replicas: {{ .Values.services.worker.external.replicas }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-backend-external-worker
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      labels:
        app: {{ .Release.Name }}-backend-external-worker
    spec:
{{ include "imagePullSecretTemplate" . | nindent 6 }}
      {{- if .Values.files }}
      volumes:
      - configMap:
          name: {{ .Release.Name }}-mount-file
        name: {{ .Release.Name }}-mount-file
      {{- end }}
      containers:
{{- if .Values.image.internal }}
        - image: {{ .Values.image.registry | trimSuffix "/" }}{{ if .Values.image.registry }}/{{ end }}datasaur/backend-on-premise:{{ .Values.image.dockerTag }}
{{- else }}
        - image: {{ .Values.image.registry | trimSuffix "/" }}{{ if .Values.image.registry }}/{{ end }}datasaur/backend-on-premise:{{ .Values.image.dockerTag }}
{{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: {{ .Release.Name }}-backend-external-worker
          envFrom:
            - configMapRef:
                name: datasaur-env
            - secretRef:
                name: datasaur-secret
          env:
            - name: APP_URL
              value: https://$(HOST)
            - name: ASSETS_URL
              value: https://$(HOST)
            - name: ENABLE_DOCUMENT_STATISTIC_EXECUTOR
              value: "true"
            - name: ENABLE_DOCUMENT_CONVERSION_EXECUTOR
              value: "true"
            - name: ENABLE_MESSAGE_QUEUE_CONSUMER
              value: "true"
            - name: CONSUMED_QUEUES
              value: external,action
            - name: RABBITMQ_PREFETCH_COUNT_EXTERNAL
              value: "1"
            - name: RABBITMQ_PREFETCH_COUNT_ACTION
              value: "1"
          {{- if .Values.files }}
          volumeMounts:
          {{- $relname := .Release.Name -}}
          {{- range .Values.files }}
            - name: {{ $relname }}-mount-file
              mountPath: {{ .mountPath }}
              subPath: {{ .name }}
          {{- end }}
          {{- end }}
          {{- if not .Values.services.worker.external.resources.auto }}
          resources:
            limits:
              cpu: {{ .Values.services.worker.external.resources.limits.cpu }}
              memory: {{ .Values.services.worker.external.resources.limits.memory }}
            requests:
              cpu: {{ .Values.services.worker.external.resources.requests.cpu }}
              memory: {{ .Values.services.worker.external.resources.requests.memory }}
          {{- end }}
          livenessProbe:
            exec:
              command:
                - wget
                - http://localhost:8080/api/health
                - "-q"
                - "-O"
                - "-"
            failureThreshold: 3
            periodSeconds: 20
            timeoutSeconds: 2
          readinessProbe:
            exec:
              command:
                - wget
                - http://localhost:8080/api/health
                - "-q"
                - "-O"
                - "-"
            failureThreshold: 30
            periodSeconds: 5
            timeoutSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend-external-worker-service
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-backend-external-worker
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
{{- if .Values.services.worker.external.autoscaling.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-backend-external-worker-autoscaler
  labels:
    app: {{ .Release.Name }}-backend-external-worker-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-backend-external-worker
  minReplicas: {{ .Values.services.worker.external.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.services.worker.external.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.services.worker.external.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.services.worker.external.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.services.worker.external.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.services.worker.external.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
