apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend-service
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name }}-backend
  name: {{ .Release.Name }}-backend
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
spec:
  {{- if not .Values.services.backend.autoscaling.enabled }}
  replicas: {{ .Values.services.backend.replicas }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-backend
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      labels:
        app: {{ .Release.Name }}-backend
    spec:
{{ include "imagePullSecretTemplate" . | nindent 6 }}
{{- if .Values.clusterSettings.backendServiceAccount }}
      serviceAccountName: {{ .Values.clusterSettings.backendServiceAccount }}
{{- end }}
      {{- if .Values.files }}
      volumes:
      - configMap:
          name: {{ .Release.Name }}-mount-file
        name: {{ .Release.Name }}-mount-file
      {{- end }}
      containers:
{{- if .Values.image.internal }}
        - image: {{ .Values.image.registry | trimSuffix "/" }}{{ if .Values.image.registry }}/{{ end }}vulcan-ai/vulcan/backend:{{ .Values.image.dockerTag }}
{{- else }}
        - image: {{ .Values.image.registry | trimSuffix "/" }}{{ if .Values.image.registry }}/{{ end }}datasaur/backend-on-premise:{{ .Values.image.dockerTag }}
{{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: {{ .Release.Name }}-backend
          envFrom:
            - configMapRef:
                name: datasaur-env
            - secretRef:
                name: datasaur-secret
{{- if .Values.extraEnvsFrom }}
{{ tpl ( toYaml .Values.extraEnvsFrom ) . | indent 12 }}
{{- end }}
          env:
            - name: APP_URL
              value: https://$(HOST)
            - name: ASSETS_URL
              value: https://$(HOST)
{{- if .Values.elasticsearch.enabled }}
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-elasticsearch-es-elastic-user
                  key: elastic
{{- end }}
{{- if .Values.ingress.llmLabs.host }}
            - name: ELASTICSEARCH_VECTOR_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-elasticsearch-es-elastic-user
                  key: elastic
{{- end }}
          {{- if .Values.files }}
          volumeMounts:
          {{- $relname := .Release.Name -}}
          {{- range .Values.files }}
            - name: {{ $relname }}-mount-file
              mountPath: {{ .mountPath }}
              subPath: {{ .name }}
          {{- end }}
          {{- end }}
          {{- if not .Values.services.backend.resources.auto }}
          resources:
            limits: 
              cpu: {{ .Values.services.backend.resources.limits.cpu }}
              memory: {{ .Values.services.backend.resources.limits.memory }}
            requests: 
              cpu: {{ .Values.services.backend.resources.requests.cpu }}
              memory: {{ .Values.services.backend.resources.requests.memory }}
          {{- end }}
          livenessProbe:
            exec:
              command:
                - wget
                - http://localhost:8080/api/health
                - "-q"
                - "-O"
                - "-"
            failureThreshold: 20
            periodSeconds: 6
            timeoutSeconds: 2
          readinessProbe:
            exec:
              command:
                - wget
                - http://localhost:8080/api/health
                - "-q"
                - "-O"
                - "-"
            failureThreshold: 30
            periodSeconds: 5
            timeoutSeconds: 2
{{- if .Values.services.backend.autoscaling.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-backend-autoscaler
  labels:
    app: {{ .Release.Name }}-backend-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-backend
  minReplicas: {{ .Values.services.backend.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.services.backend.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.services.backend.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target: 
          type: Utilization
          averageUtilization: {{ .Values.services.backend.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.services.backend.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target: 
          type: Utilization
          averageUtilization: {{ .Values.services.backend.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
