{{- if .Values.ingress.host }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend-service
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-frontend
  ports:
    - protocol: TCP
      port: 3080
      targetPort: 3080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name }}-frontend
  name: {{ .Release.Name }}-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-frontend
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      labels:
        app: {{ .Release.Name }}-frontend
    spec:
{{ include "imagePullSecretTemplate" . | nindent 6 }}
      containers:
{{- if .Values.image.internal }}
        - image: {{ .Values.image.registry | trimSuffix "/" }}{{ if .Values.image.registry }}/{{ end }}vulcan-ai/vulcan/frontend:{{ .Chart.AppVersion }}
{{- else }}
        - image: {{ .Values.image.registry | trimSuffix "/" }}{{ if .Values.image.registry }}/{{ end }}{{ .Values.imageCredentials.prefix | default "datasaur" }}/frontend-on-premise:{{ .Chart.AppVersion }}
{{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: {{ .Release.Name }}-frontend
          volumeMounts:
            - name: frontend-env
              mountPath: /usr/src/app/.env
              subPath: .env
          envFrom:
            - configMapRef:
                name: datasaur-env
            - secretRef:
                name: datasaur-secret
          env:
            - name: APP_URL
              value: https://$(HOST)
            - name: ASSETS_URL
              value: https://$(HOST)
          {{- if not .Values.services.frontend.resources.auto }}
          resources:
            limits: 
              cpu: {{ .Values.services.frontend.resources.limits.cpu }}
              memory: {{ .Values.services.frontend.resources.limits.memory }}
            requests: 
              cpu: {{ .Values.services.frontend.resources.requests.cpu }}
              memory: {{ .Values.services.frontend.resources.requests.memory }}
          {{- end }}
      volumes:
        - name: frontend-env
          configMap:
            name: frontend-env
            items:
              - key: .env
                path: .env
{{- end }}
