{{- if .Values.loki.grafana.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-grafana-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/proxy-body-size: "{{ .Values.ingress.proxyBodySize }}"
{{- if .Values.tls.ca }}
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
    nginx.ingress.kubernetes.io/auth-tls-secret: "{{ .Release.Namespace }}/{{ .Release.Name }}-datasaur-tls-ca"
    nginx.ingress.kubernetes.io/auth-tls-verify-depth: "{{ .Values.tls.verifyDepth }}"
{{- if .Values.tls.errorPage }}
    nginx.ingress.kubernetes.io/auth-tls-error-page: {{ .Values.tls.errorPage }}
{{- end }}
{{- end }}
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Release.Name }}-datasaur-tls
  rules:
    # - host: {{ .Values.ingress.host }}
    - http:
        paths:
          - path: /grafana/(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-grafana
                port:
                  number: 80
{{- end }}
