{{- if .Values.ingress.llm.host }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-datasaur-llm-lab-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$1$2
    nginx.ingress.kubernetes.io/proxy-body-size: "{{ .Values.ingress.proxyBodySize }}"
{{- if .Values.llmTls.ca }}
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
    nginx.ingress.kubernetes.io/auth-tls-secret: "{{ .Release.Namespace }}/{{ .Release.Name }}-datasaur-llm-lab-ca"
    nginx.ingress.kubernetes.io/auth-tls-verify-depth: "{{ .Values.llmTls.verifyDepth }}"
{{- if .Values.llmTls.errorPage }}
    nginx.ingress.kubernetes.io/auth-tls-error-page: {{ .Values.llmTls.errorPage }}
{{- end }}
{{- end }}
{{- if .Values.ingress.annotations }}
{{ tpl ( toYaml .Values.ingress.annotations ) . | indent 4 }}
{{- end }}
spec:
{{- if .Values.llmTls.secretName }}
  tls:
    - hosts:
        - {{ .Values.ingress.llm.host }}
      secretName: {{ .Values.llmTls.secretName }}
{{- else }}
  tls:
    - hosts:
        - {{ .Values.ingress.llm.host }}
      secretName: {{ .Release.Name }}-datasaur-llm-lab-tls
{{- end }}
  rules:
    - host: {{ .Values.ingress.llm.host }}
      http:
        paths:
{{- if .Values.services.urlInspector.proxy }}
          - path: /(api/url-inspector|api/static/serve-private|api/static/proxy/upload)(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-url-inspector-service
                port:
                  number: 8080
{{- else }}
          - path: /(api/url-inspector|api/static/serve-private)(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-url-inspector-service
                port:
                  number: 8080
{{- end }}
          - path: /(api|admin|graphql|auth|export)(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-backend-service
                port:
                  number: 8080
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-llm-lab-frontend-service
                port:
                  number: 7080
{{- end }}
