{{- if .Values.loki.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-loki-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: "{{ .Values.ingress.proxyBodySize }}"
{{- if .Values.loki.auth.username }}
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: {{ .Release.Name }}-loki-auth
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required - ok"
{{- end }}
{{- if .Values.tls.ca }}
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
    nginx.ingress.kubernetes.io/auth-tls-secret: "{{ .Release.Namespace }}/{{ .Release.Name }}-datasaur-tls-ca"
    nginx.ingress.kubernetes.io/auth-tls-verify-depth: "{{ .Values.tls.verifyDepth }}"
{{- if .Values.tls.errorPage }}
    nginx.ingress.kubernetes.io/auth-tls-error-page: {{ .Values.tls.errorPage }}
{{- end }}
{{- end }}
{{- if .Values.ingress.annotations }}
{{ tpl ( toYaml .Values.ingress.annotations ) . | indent 4 }}
{{- end }}
spec:
{{- if .Values.tls.secretName }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.tls.secretName }}
{{- else }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Release.Name }}-datasaur-tls
{{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /loki
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-loki
                port:
                  number: 3100
{{- end }}
