{{- if .Values.imageCredentials.username }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-image-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
