apiVersion: v1
data:
  tls.crt: {{ .Values.tls.cert }}
  tls.key: {{ .Values.tls.key }}
kind: Secret
metadata:
  name: {{ .Release.Name }}-datasaur-tls
type: kubernetes.io/tls
{{- if .Values.tls.ca }}
---
apiVersion: v1
data:
  ca.crt: {{ .Values.tls.ca }}
kind: Secret
metadata:
  name: {{ .Release.Name }}-datasaur-tls-ca
type: Opaque
{{- end }}
