apiVersion: v1
kind: ConfigMap
metadata:
  name: datasaur-env
data: 
  API_URL: {{ .Release.Name }}-backend-service:8080
  DATABASE_HOST: {{ .Release.Name }}-mariadb-service
  REDIS_HOST: {{ .Release.Name }}-redis-service
  RABBITMQ_URLS: amqp://_main._tcp.{{ .Release.Name }}-rabbitmq-service:5672
  APACHE_TIKA_SERVICE_HOST: http://{{ .Release.Name }}-apache-tika-service:9998
  DOCUMENT_CONVERTER_SERVICE_HOST: http://{{ .Release.Name }}-document-converter-service:3000
  LANGUAGE_TOOL_SERVICE_ENDPOINT: http://{{ .Release.Name }}-language-tool-service:8010/v2/check
  PRESIDIO_ANALYZER_ENDPOINT: http://{{ .Release.Name }}-presidio-analyzer-service:3000/analyze
  WAVEFORM_PEAKS_GENERATOR_HOST: http://{{ .Release.Name }}-audiowaveform-generator-service:5005
  URL_INSPECTOR_INGRESS_URL: https://{{ .Values.ingress.host }}
  URL_INSPECTOR_INGRESS_HOST: {{ .Values.ingress.host }}
  MAX_TOKENS_PER_SENTENCE: "3000"
  ENABLE_DISTILBERT_AUTO_LABEL: "false"
{{- if .Values.elasticsearch.enabled }}
  ELASTICSEARCH_NODE: http://{{ .Release.Name }}-elasticsearch-es-http:9200
  ENABLE_ANALYTICS: "true"
  ENABLE_CUSTOM_REPORT_BUILDER: "true"
  DEFAULT_ANALYTICS_DATASOURCE: ELASTIC
  DEFAULT_ANALYTICS_CRB_DATASOURCE: ELASTIC
{{- end }}
{{- if .Values.ingress.llmLabs.host }}
  ELASTICSEARCH_VECTOR_DB_NODE: http://{{ .Release.Name }}-elasticsearch-es-http:9200
{{- end }}
{{- if .Values.services.urlInspector.proxy }}
  ENABLE_PROJECT_CREATION_WITH_PROXY: "true"
  SESSION_DOMAIN: {{ .Values.ingress.sessionDomain }}
  UPLOAD_FILE_PROXY_URL: https://{{ if .Values.ingress.uploadProxyHost }}{{ .Values.ingress.uploadProxyHost }}{{ else }}{{ .Values.ingress.host }}{{ end }}/api/static/proxy/upload
  MAX_DOCUMENT_FILE_SIZE: "52428800"
  MAX_AUDIO_FILE_SIZE: "{{ div .Values.services.urlInspector.resources.limits.memory 4 }}"
  MAX_IMAGE_FILE_SIZE: "{{ div .Values.services.urlInspector.resources.limits.memory 4 }}"
  MAX_REQUEST_SIZE: "{{ div (mul .Values.services.urlInspector.resources.limits.memory 3) 4 }}"
{{- end }}
{{- if .Values.services.languageCrunch.enabled }}
  DATASAUR_EXTENSION_AUTO_LABEL_HOST: http://{{ .Release.Name }}-language-crunch-service:8080
  ENABLE_SPACY_AUTO_LABEL: "true"
{{- end }}
{{- if .Values.analytics.enabled }}
  ENABLE_GLAIR_ANALYTICS: "true"
  ENABLE_NEW_ANALYTICS: "true"
  ENABLE_CUSTOM_REPORT_BUILDER: "true"
  METABASE_BASE_URL: http://{{ .Release.Name }}-metabase
  METABASE_SECRET_KEY: "{{ .Values.metabase.embedding_key }}"
{{- end }}
{{- if .Values.services.coreNlp.enabled }}
  DATASAUR_EXTENSION_AUTO_LABEL_CORENLP_NER_ENDPOINT: http://{{ .Release.Name }}-nltk-provider-service:9090/tag/corenlp/ner
  DATASAUR_EXTENSION_AUTO_LABEL_CORENLP_POS_ENDPOINT: http://{{ .Release.Name }}-nltk-provider-service:9090/tag/corenlp/pos
  DATASAUR_EXTENSION_AUTO_LABEL_NLTK_ENDPOINT: http://{{ .Release.Name }}-nltk-provider-service:9090/tag/default/pos
  ENABLE_NLTK_AUTO_LABEL: "true"
  ENABLE_CORENLP_AUTO_LABEL: "true"
{{- end }}
{{- if .Values.services.sparknlpProvider.enabled }}
  DATASAUR_EXTENSION_AUTO_LABEL_SPARKNLP_NER_ENDPOINT: http://{{ .Release.Name }}-sparknlp-provider-service:9091/tag/en.ner
  DATASAUR_EXTENSION_AUTO_LABEL_SPARKNLP_POS_ENDPOINT: http://{{ .Release.Name }}-sparknlp-provider-service:9091/tag/en.pos
  ENABLE_SPARKNLP_AUTO_LABEL: "true"
{{- end }}
{{- if .Values.services.datasaurDinamic.enabled }}
  SHERLOCK_DATASAUR_ASSIST_ROW_BASED_ENDPOINT: http://{{ .Release.Name }}-datasaur-dinamic-service:8002/api/v1
  ENABLE_DATASAUR_DINAMIC_ROW_BASED: "true"
  ENABLE_DATASAUR_DINAMIC_ROW_BASED_PER_TEAM: "false"
  ENABLE_DATASAUR_DINAMIC_HUGGINGFACE_AUTOTRAIN: "true"
  ENABLE_DATASAUR_PREDICTIVE_ROW_BASED: "true"
  ENABLE_DATASAUR_PREDICTIVE_ROW_BASED_PER_TEAM: "false"
  ENABLE_LABEL_ERROR_DETECTION_ROW_BASED: "true"
  ENABLE_LABEL_ERROR_DETECTION_ROW_BASED_PER_TEAM: "false"
{{- end }}
{{- if .Values.services.dataProgramming.enabled }}
  SHERLOCK_DATA_PROGRAMMING_ENDPOINT: http://{{ .Release.Name }}-data-programming-service:8001/api/v1
  DATA_PROGRAMMING_ROW_BASED_PROVIDER: STEGOSAURUS
  ENABLE_DATA_PROGRAMMING_ROW_BASED: "true"
  ENABLE_DATA_PROGRAMMING_TOKEN_BASED: "true"
  ENABLE_DATA_PROGRAMMING_PER_TEAM: "false"
{{- end }}
{{- if .Values.env }}
{{ .Values.env | toYaml | indent 2 }}
{{- end }}
