apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-alert-provisioning
data:
{{- if .Values.loki.alerting }}
{{ tpl ( toYaml .Values.loki.alerting ) . | indent 1 }}
{{- else }}
  provision: |
    null
{{- end }}
