apiVersion: v1
kind: ConfigMap
metadata:
  name: intelligence-env
data:
  NLTK_PROVIDER_CORENLP_URL: http://{{ .Release.Name }}-core-nlp-service:9000
  NLTK_PROVIDER_PORT: "9090"
  SPARKNLP_PORT: "9091"

  # Datasaur Dinamic environment variables
  DATASAUR_ASSIST_VULCAN_BASIC_AUTH: {{ .Values.intelligence.datasaurAssist.authKey }}
  DATASAUR_ASSIST_VULCAN_HOST: http://{{ .Release.Name }}-backend-service:8080
  # the credentials here are used to connect to object storage and assuming role for sagemaker access
  # currently Datasaur Dinamic only support s3
  DATASAUR_ASSIST_OBJECT_STORAGE_BUCKET: {{ .Values.intelligence.datasaurAssist.objectStorageBucket }}
  DATASAUR_ASSIST_OBJECT_STORAGE_BUCKET_PREFIX: {{ .Values.intelligence.datasaurAssist.objectStorageBucketPrefix }}
  DATASAUR_ASSIST_OBJECT_STORAGE_ENDPOINT:   {{ .Values.intelligence.datasaurAssist.objectStorageEndpoint }}
  DATASAUR_ASSIST_AWS_REGION:   {{ .Values.intelligence.datasaurAssist.awsRegion }}
  DATASAUR_ASSIST_AWS_ACCESS_KEY: {{ .Values.intelligence.datasaurAssist.awsAccessKey }}
  DATASAUR_ASSIST_AWS_SECRET_KEY:  {{ .Values.intelligence.datasaurAssist.awsSecretKey }}
  DATASAUR_ASSIST_CELERY_BROKER: redis://{{ .Release.Name }}-redis-service:6379
