{{- if .Values.loki.auth.username }}
apiVersion: v1
data:
  auth: {{ (htpasswd .Values.loki.auth.username .Values.loki.auth.password) | b64enc | quote }}
kind: Secret
metadata:
  name: {{ .Release.Name }}-loki-auth
type: Opaque
{{- end }}
