{{- if .Values.metabase_importer.enabled  }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-metabase-importer-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  AWS_ACCESS_KEY: {{ required "AWS_ACCESS_KEY is required" .Values.metabase_importer.secret.aws.access_key | quote }}
  AWS_SECRET_KEY: {{ required "AWS_SECRET_KEY is required" .Values.metabase_importer.secret.aws.secret_key | quote }}
  AWS_REGION: {{ required "AWS_REGION is required" .Values.metabase_importer.secret.aws.region | quote }}
  AWS_S3_BUCKET: {{ required "AWS_S3_BUCKET is required" .Values.metabase_importer.secret.aws.s3_bucket | quote }}
  DB_HOST: {{ required "MYSQL_HOST is required" .Values.metabase_importer.secret.db.host | quote }}
  DB_NAME: {{ required "MYSQL DB NAME is required" .Values.metabase_importer.secret.db.name | quote }}
  DB_USER: {{ required "MYSQL USER is required" .Values.metabase_importer.secret.db.user | quote }}
  DB_PASS: {{ required "MYSQL PASSWORD is required" .Values.metabase_importer.secret.db.pass | quote }}
  DB_PORT: {{ required "MYSQL PORT is required" .Values.metabase_importer.secret.db.port | quote }}
{{- end }}