{{- if .Values.metabaseImporter.enabled  }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-metabase-importer-secret
type: Opaque
stringData:
  AWS_ACCESS_KEY: {{ required "AWS_ACCESS_KEY is required" .Values.metabaseImporter.secret.aws.access_key | quote }}
  AWS_SECRET_KEY: {{ required "AWS_SECRET_KEY is required" .Values.metabaseImporter.secret.aws.secret_key | quote }}
  AWS_REGION: {{ required "AWS_REGION is required" .Values.metabaseImporter.secret.aws.region | quote }}
  AWS_S3_BUCKET: {{ required "AWS_S3_BUCKET is required" .Values.metabaseImporter.secret.aws.s3_bucket | quote }}
  DB_HOST: {{ .Release.Name }}-metabasemysql
  DB_NAME: {{ .Values.metabasemysql.auth.database }}
  DB_USER: root
  DB_PASS: {{ .Values.metabasemysql.auth.rootPassword }}
  DB_PORT: "3306"
{{- end }}