{{- if .Values.services.audiowaveformGenerator.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-audiowaveform-generator-service
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-audiowaveform-generator
  ports:
    - protocol: TCP
      port: 5005
      targetPort: 5005
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name }}-audiowaveform-generator
  name: {{ .Release.Name }}-audiowaveform-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-audiowaveform-generator
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-audiowaveform-generator
    spec:
{{ include "imagePullSecretTemplate" . | nindent 6 }}
      containers:
        - image: {{ .Values.image.registry | trimSuffix "/" }}{{ if .Values.image.registry }}/{{ end }}vulcan-ai/vulcan/audiowaveform-generator:{{ .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: {{ .Release.Name }}-audiowaveform-generator
          envFrom:
            - configMapRef:
                name: datasaur-env
            - secretRef:
                name: datasaur-secret
{{- end -}}
