{{- if .Values.services.datasaurDinamic.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-datasaur-dinamic-flower-service
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-datasaur-dinamic-flower
  ports:
    - protocol: TCP
      port: 5555
      targetPort: 5555
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name }}-datasaur-dinamic-flower
  name: {{ .Release.Name }}-datasaur-dinamic-flower
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-datasaur-dinamic-flower
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-datasaur-dinamic-flower
    spec:
{{ include "imagePullSecretTemplate" . | nindent 6 }}
      containers:
{{- if .Values.dockerHub.enabled }}
        - image: mher/flower:2.0
{{- else }}
        - image: {{ .Values.image.registry | trimSuffix "/" }}{{ if .Values.image.registry }}/{{ end }}mher/flower:2.0
          imagePullPolicy: {{ .Values.image.pullPolicy }}
{{- end }}
          command: ["celery", "flower"]
          name: {{ .Release.Name }}-datasaur-dinamic-flower
          env:
            - name: CELERY_BROKER_URL
              value: redis://redis:6379
            - name: FLOWER_BASIC_AUTH
              value: {{ .Values.intelligence.datasaurDinamic.flowerAuthUserName }}:{{.Values.intelligence.datasaurDinamic.flowerAuthPassword}}
                
{{- end -}}
