{{- if or .Values.elasticsearch.enabled .Values.ingress.llmLabs.host }}
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: {{ .Release.Name }}-elasticsearch
  annotations:
    "helm.sh/hook": post-install,post-upgrade
spec:
  version: 8.10.4
  volumeClaimDeletePolicy: DeleteOnScaledownOnly
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  nodeSets:
  - name: master-nodes
    count: {{ .Values.elasticsearch.nodeCount }}
    podTemplate:
      spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
            runAsUser: 0
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
    config:
      node.roles: ["master", "data" ,"data_content" ,"data_hot", "data_warm", "data_cold", "data_frozen", "ml", "ingest", "remote_cluster_client", "transform"]
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.elasticsearch.storage }}
{{- end }}
