{{- if .Values.services.languageTool.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-language-tool-service
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-language-tool
  ports:
    - protocol: TCP
      port: 8010
      targetPort: 8010
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name }}-language-tool
  name: {{ .Release.Name }}-language-tool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-language-tool
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-language-tool
    spec:
{{ include "imagePullSecretTemplate" . | nindent 6 }}
      containers:
{{- if .Values.dockerHub.enabled }}
        - image: erikvl87/languagetool
{{- else }}
        - image: {{ .Values.image.registry | trimSuffix "/" }}{{ if .Values.image.registry }}/{{ end }}erikvl87/languagetool:6.3-1
          imagePullPolicy: {{ .Values.image.pullPolicy }}
{{- end }}
          name: {{ .Release.Name }}-language-tool
{{- end -}}
