apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: {{ .Release.Name }}-migrator
  name: {{ .Release.Name }}-migrator
spec:
  ttlSecondsAfterFinished: 30
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-migrator
      annotations:
        "helm.sh/hook": post-install,post-upgrade
        "helm.sh/hook-weight": "1"
    spec:
{{ include "imagePullSecretTemplate" . | nindent 6 }}
      containers:
{{- if .Values.image.internal }}
        - image: {{ .Values.image.registry | trimSuffix "/" }}{{ if .Values.image.registry }}/{{ end }}vulcan-ai/vulcan/backend:{{ .Values.image.dockerTag }}
{{- else }}
        - image: {{ .Values.image.registry | trimSuffix "/" }}{{ if .Values.image.registry }}/{{ end }}{{ .Values.imageCredentials.productCode | default "datasaur" }}/backend-on-premise:{{ .Values.image.dockerTag }}
{{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: {{ .Release.Name }}-backend-migrator
          command: ["/usr/src/app/migration.sh"]
          envFrom:
            - configMapRef:
                name: datasaur-env
            - secretRef:
                name: datasaur-secret
{{- if or .Values.elasticsearch.enabled .Values.ingress.llmLabs.host }}
          env:
{{- end }}
{{- if .Values.elasticsearch.enabled }}
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-elasticsearch-es-elastic-user
                  key: elastic
{{- end }}
{{- if .Values.ingress.llmLabs.host }}
            - name: ELASTICSEARCH_VECTOR_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-elasticsearch-es-elastic-user
                  key: elastic
{{- end }}
      restartPolicy: Never
